lumo_file_version = "0.1.0"
software_version = "0.0.0"

[file_names]
recordingdata_file = "recordingdata.toml"
event_file = "events.toml"
hardware_file = "hardware.toml"
log_file = "lumo.log"

[[intensity_files]]
file_name = "intensity_01.bin"
time_range = [0.22,1189.79]

